// Mocks generated by Mockito 5.4.4 from annotations
// in kitabghar/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i9;

import 'package:dartz/dartz.dart' as _i2;
import 'package:kitabghar/core/error/failures.dart' as _i5;
import 'package:kitabghar/features/auth/domain/entities/auth_entity.dart'
    as _i6;
import 'package:kitabghar/features/auth/domain/repositories/auth_reposity.dart'
    as _i3;
import 'package:kitabghar/features/auth/domain/usecases/login_usercase.dart'
    as _i10;
import 'package:kitabghar/features/auth/domain/usecases/logout_usecase.dart'
    as _i12;
import 'package:kitabghar/features/auth/domain/usecases/register_usecase.dart'
    as _i11;
import 'package:kitabghar/features/books/domain/entities/books_entities.dart'
    as _i8;
import 'package:kitabghar/features/books/domain/repositories/books_repository.dart'
    as _i7;
import 'package:kitabghar/features/books/domain/usecases/create_books_usecase.dart'
    as _i14;
import 'package:kitabghar/features/books/domain/usecases/delete_books_usecase.dart'
    as _i15;
import 'package:kitabghar/features/books/domain/usecases/get_all_books_usecase.dart'
    as _i13;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i3.IAuthRepository {
  MockIAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> register(_i6.AuthEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [entity],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #register,
            [entity],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthEntity>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.AuthEntity>>.value(
            _FakeEither_0<_i5.Failure, _i6.AuthEntity>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> logout(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #logout,
          [email],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #logout,
            [email],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}

/// A class which mocks [IBooksRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBooksRepository extends _i1.Mock implements _i7.IBooksRepository {
  MockIBooksRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.BooksEntity>>> getAllBooks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllBooks,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i8.BooksEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.BooksEntity>>(
          this,
          Invocation.method(
            #getAllBooks,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.BooksEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.BooksEntity>> createBook(
    _i8.BooksEntity? book, {
    _i9.File? image,
    required String? token,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBook,
          [book],
          {
            #image: image,
            #token: token,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.BooksEntity>>.value(
            _FakeEither_0<_i5.Failure, _i8.BooksEntity>(
          this,
          Invocation.method(
            #createBook,
            [book],
            {
              #image: image,
              #token: token,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.BooksEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> deleteBook(
    String? id, {
    required String? token,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBook,
          [id],
          {#token: token},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #deleteBook,
            [id],
            {#token: token},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i10.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthEntity>> call(
          _i10.LoginParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.AuthEntity>>.value(
            _FakeEither_0<_i5.Failure, _i6.AuthEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthEntity>>);
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i11.RegisterUseCase {
  MockRegisterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> call(_i6.AuthEntity? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i12.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> call(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [email],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [email],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}

/// A class which mocks [GetAllBooksUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllBooksUseCase extends _i1.Mock
    implements _i13.GetAllBooksUseCase {
  MockGetAllBooksUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.BooksEntity>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i8.BooksEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.BooksEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.BooksEntity>>>);
}

/// A class which mocks [CreateBooksUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateBooksUseCase extends _i1.Mock
    implements _i14.CreateBooksUseCase {
  MockCreateBooksUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.BooksEntity>> call(
          _i14.CreateBooksParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.BooksEntity>>.value(
            _FakeEither_0<_i5.Failure, _i8.BooksEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.BooksEntity>>);
}

/// A class which mocks [DeleteBooksUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteBooksUseCase extends _i1.Mock
    implements _i15.DeleteBooksUseCase {
  MockDeleteBooksUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> call(
          _i15.DeleteBooksParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}
